### ISSUE TITLE
JWT Firebase idToken validation

### ISSUE THREAD

**Issue by alextekartik** [corsac-dart/jwt#15]
Thanks for you work that I have used to parse firebase rsa public key.

I had to add the following overriden dependencies to work with the latest rsa_pkcs that fixes the issue (https://github.com/amaurel/rsa_pkcs/issues/8) that could allow [jwt firebase validation](https://firebase.google.com/docs/auth/admin/verify-id-tokens)

```
  rsa_pkcs: '>=1.1.2'
  asn1lib: '>=0.6.4'
```

I can do a pull request if you want

**Comment by pulyaevskiy** [comment]
I published 0.2.2 with upgraded dependencies. Thanks for reporting!

**Comment by alextekartik** [comment]
Thanks!
