### ISSUE TITLE
Re-introduce RS256 signer when dependencies are ready for Dart 2

### ISSUE THREAD

**Issue by pulyaevskiy** [corsac-dart/jwt#2]
Blockers:

* [x] https://github.com/amaurel/rsa_pkcs/pull/4
* [x] https://github.com/PointyCastle/pointycastle/issues/131

**Comment by aloisdeniel** [comment]
The first one is now fixed !

**Comment by joaoritter** [comment]
Can this be addressed now? Seems like the blockers have cleared. Thank you!

**Comment by pulyaevskiy** [comment]
Looking at the referenced issues they are still not resolved. 
The rsa issue even though merged haven't been published to Pub.
Pointycastle issue is still open. 

Wondering if you happen to know about alternatives?

**Comment by TomLiu-GitHub** [comment]
+1

**Comment by emadfarag** [comment]
Here's a pull request to fix this: https://github.com/corsac-dart/jwt/pull/11

**Comment by pulyaevskiy** [comment]
#11 merged and released as 0.2.0.

Thanks!
